name: Release

on:
  push:
    tags:
      - "nightly-*"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: cargo test
      - run: cargo doc --lib
      - run: RUSTDOCFLAGS="--html-in-header scripts/katex-header.html" cargo doc --lib --no-deps      
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./target/doc
          target-folder: ${{ github.ref_name }}
