name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy --all-features -- -D warnings
      - name: Tests
        run: cargo test --all-features -- --test-threads=1
      - name: Docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps