name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy --all --all-features
      - name: Tests
        run: cargo test --all --all-features -- --test-threads=1